#pragma once

#define ORYX_CONFIGURATOR

#define CAPS_LOCK_STATUS

// #undef RGB_DISABLE_TIMEOUT
// #define RGB_DISABLE_TIMEOUT 900000 // In miliseconds -- 15 minutes

#undef MOUSEKEY_TIME_TO_MAX  
#define MOUSEKEY_TIME_TO_MAX        30

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX  0

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// #define RGBLIGHT_COLOR_LAYER_0 0x00, 0x00, 0xFF
// #define RGBLIGHT_COLOR_LAYER_1 0x00, 0x00, 0xFF
// #define RGBLIGHT_COLOR_LAYER_2 0xFF, 0x00, 0x00
// #define RGBLIGHT_COLOR_LAYER_3 0x00, 0xFF, 0x00
// #define RGBLIGHT_COLOR_LAYER_4 0xFF, 0xFF, 0x00
// #define RGBLIGHT_COLOR_LAYER_5 0x00, 0xFF, 0xFF
// #define RGBLIGHT_COLOR_LAYER_6 0xFF, 0x00, 0xFF
// #define RGBLIGHT_COLOR_LAYER_7 0xFF, 0xFF, 0xFF